import { Artist } from './interfaces';

export const ARTISTS: Artist[] = [
  {
    name: 'Random',
  },
  {
    id: 13,
    genre: ['Rap'],
    name: 'Eminem',
    nationality: 'international',
    image:
      'https://e-cdns-images.dzcdn.net/images/artist/19cc38f9d69b352f718782e7a22f9c32/500x500-000000-80-0-0.jpg',
  },
  {
    id: 3,
    genre: ['Rap'],
    name: 'Snoop Dogg',
    nationality: 'international',
    image:
      'https://e-cdns-images.dzcdn.net/images/artist/a423dd42b7394eeacc882be8ac633eee/500x500-000000-80-0-0.jpg',
  },
  {
    id: 1309,
    genre: ['Rap'],
    name: 'JAY-Z',
    nationality: 'international',
    image:
      'https://e-cdns-images.dzcdn.net/images/artist/90fab088c4d091618e7386f688803673/500x500-000000-80-0-0.jpg',
  },
  {
    id: 246791,
    genre: ['Rap'],
    name: 'Drake',
    nationality: 'international',
    image:
      'https://e-cdns-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/500x500-000000-80-0-0.jpg',
  },
  {
    id: 230,
    genre: ['Rap'],
    name: 'Kanye West',
    nationality: 'international',
    image:
      'https://e-cdns-images.dzcdn.net/images/artist/bb76c2ee3b068726ab4c37b0aabdb57a/500x500-000000-80-0-0.jpg',
  },
  {
    id: 74309,
    genre: ['Rap'],
    name: 'Lil Wayne',
    nationality: 'international',
    image:
      'https://e-cdns-images.dzcdn.net/images/artist/2342b756645ad50f80215785d218bca8/500x500-000000-80-0-0.jpg',
  },
  {
    id: 64333,
    genre: ['Rap'],
    name: 'Flo Rida',
    nationality: 'international',
    image:
      'https://e-cdns-images.dzcdn.net/images/artist/99386bbd6963abb7da4f713c8a6411ff/500x500-000000-80-0-0.jpg',
  },

  {
    id: 125278382,
    genre: ['Rap'],
    name: 'Tupac Shakur',
    nationality: 'international',
  },
  {
    id: 267,
    genre: ['Rap'],
    name: 'DMX',
    nationality: 'international',
  },
  {
    id: 2519,
    genre: ['Rap'],
    name: 'The Notorious B.I.G',
    nationality: 'international',
  },
  {
    id: 66,
    genre: ['Rap'],
    name: '50 Cent',
    nationality: 'international',
  },
  {
    id: 4495513,
    genre: ['Rap'],
    name: 'Travis Scott',
    nationality: 'international',
  },
  {
    id: 525046,
    genre: ['Rap'],
    name: 'Kendrick Lamar',
    nationality: 'international',
  },
  {
    id: 14456487,
    genre: ['Rap'],
    name: 'Juice WRLD',
    nationality: 'international',
  },
  {
    id: 105,
    genre: ['Rap'],
    name: 'Nelly',
    nationality: 'international',
  },
  {
    id: 2353,
    genre: ['Rap'],
    name: 'Ice Cube',
    nationality: 'international',
  },
  {
    id: 73,
    genre: ['Rap'],
    name: 'Nas',
    nationality: 'international',
  },
  {
    id: 763,
    genre: ['Rap'],
    name: 'Dr. Dre',
    nationality: 'international',
  },
  {
    id: 1,
    genre: ['Rock', 'Pop'],
    name: 'The Beatles',
    nationality: 'international',
  },
  {
    id: 1125,
    genre: ['Rock', 'Pop'],
    name: 'Elvis Presley',
    nationality: 'international',
  },
  {
    id: 259,
    genre: ['Pop', 'Rock'],
    name: 'Michael Jackson',
    nationality: 'international',
  },
  {
    id: 413,
    genre: ['Pop', 'Rock'],
    name: 'Elton John',
    nationality: 'international',
  },
  {
    id: 290,
    genre: ['Pop'],
    name: 'Madonna',
    nationality: 'international',
  },
  {
    id: 848,
    genre: ['Rock'],
    name: 'Led Zeppelin',
    nationality: 'international',
  },
  {
    id: 564,
    genre: ['R&B', 'Pop'],
    name: 'Rihanna',
    nationality: 'international',
  },
  {
    id: 860,
    genre: ['Rock'],
    name: 'Pink Floyd',
    nationality: 'international',
  },
  {
    id: 65,
    genre: ['R&B', 'Pop'],
    name: 'Mariah Carey',
    nationality: 'international',
  },
  {
    id: 12246,
    genre: ['Pop'],
    name: 'Taylor Swift',
    nationality: 'international',
  },
  {
    id: 412,
    genre: ['Rock'],
    name: 'Queen',
    nationality: 'international',
  },
  {
    id: 174,
    genre: ['R&B', 'Pop'],
    name: 'Whitney Houston',
    nationality: 'international',
  },
  {
    id: 210,
    genre: ['Rock'],
    name: 'Eagles',
    nationality: 'international',
  },
  {
    id: 198,
    genre: ['Pop'],
    name: 'Celine Dion',
    nationality: 'international',
  },
  {
    id: 115,
    genre: ['Rock'],
    name: 'AC/DC',
    nationality: 'international',
  },
  {
    id: 11,
    genre: ['Rock'],
    name: 'The Rolling Stones',
    nationality: 'international',
  },
  {
    id: 246791,
    genre: ['Rap'],
    name: 'Drake',
    nationality: 'international',
  },
  {
    id: 145,
    genre: ['R&B', 'Pop'],
    name: 'Beyoncé',
    nationality: 'international',
  },
  {
    id: 288166,
    genre: ['Pop'],
    name: 'Justin Bieber',
    nationality: 'international',
  },
  {
    id: 384236,
    genre: ['Pop'],
    name: 'Ed Sheeran',
    nationality: 'international',
  },
  {
    id: 4762,
    genre: ['Rock'],
    name: 'Bruce Springsteen',
    nationality: 'international',
  },
  {
    id: 163,
    genre: ['Rock'],
    name: 'U2',
    nationality: 'international',
  },
  {
    id: 1005,
    genre: ['Rock'],
    name: 'Aerosmith',
    nationality: 'international',
  },
  {
    id: 186,
    genre: ['Rock'],
    name: 'Phil Collins',
    nationality: 'international',
  },
  {
    id: 180,
    genre: ['Pop'],
    name: 'ABBA',
    nationality: 'international',
  },
  {
    id: 144227,
    genre: ['Pop'],
    name: 'Katy Perry',
    nationality: 'international',
  },
  {
    id: 102,
    genre: ['Pop', 'R&B'],
    name: 'Chris Brown',
    nationality: 'international',
  },
  {
    id: 429675,
    genre: ['Pop', 'R&B'],
    name: 'Bruno Mars',
    nationality: 'international',
  },
  {
    id: 119,
    genre: ['Rock'],
    name: 'Metallica',
    nationality: 'international',
  },
  {
    id: 75491,
    genre: ['Pop'],
    name: 'Lady Gaga',
    nationality: 'international',
  },
  {
    id: 1188,
    genre: ['Pop'],
    name: 'Maroon 5',
    nationality: 'international',
  },
  {
    id: 75798,
    genre: ['Pop'],
    name: 'Adele',
    nationality: 'international',
  },
  {
    id: 1440,
    genre: ['Rock'],
    name: 'Rod Stewart',
    nationality: 'international',
  },
  {
    id: 382937,
    genre: ['Rap', 'Pop'],
    name: 'Nicki Minaj',
    nationality: 'international',
  },
  {
    id: 892,
    genre: ['Pop'],
    name: 'Coldplay',
    nationality: 'international',
  },
  {
    id: 92,
    genre: ['Rock'],
    name: 'Linkin Park',
    nationality: 'international',
  },
  {
    id: 182,
    genre: ['Rock'],
    name: 'Red Hot Chilli Peppers',
    nationality: 'international',
  },
  {
    id: 69925,
    genre: ['Pop'],
    name: 'Pink',
    nationality: 'international',
  },
  {
    id: 483,
    genre: ['Pop'],
    name: 'Britney Spears',
    nationality: 'international',
  },
  {
    id: 637,
    genre: ['Rock'],
    name: 'Bon Jovi',
    nationality: 'international',
  },
  {
    id: 663,
    genre: ['Rock'],
    name: "Guns N' Roses",
    nationality: 'international',
  },
  {
    id: 330,
    genre: ['Pop'],
    name: 'Backstreet Boys',
    nationality: 'international',
  },
  {
    id: 192,
    genre: ['Rock'],
    name: 'Eric Clapton',
    nationality: 'international',
  },
  {
    id: 1878,
    genre: ['Pop', 'R&B'],
    name: 'Prince',
    nationality: 'international',
  },
  {
    id: 1446,
    genre: ['Rock'],
    name: 'Paul McCartney',
    nationality: 'international',
  },
  {
    id: 808,
    genre: ['Rock'],
    name: 'Bob Dylan',
    nationality: 'international',
  },
  {
    id: 166,
    genre: ['R&B'],
    name: 'Stevie Wonder',
    nationality: 'international',
  },
  {
    id: 2179,
    genre: ['Rock', 'Pop'],
    name: 'The Beach Boys',
    nationality: 'international',
  },
  {
    id: 228,
    genre: ['R&B', 'Pop'],
    name: 'Alicia Keys',
    nationality: 'international',
  },
  {
    id: 3445,
    genre: ['R&B', 'Pop'],
    name: 'Lionel Richie',
    nationality: 'international',
  },
  {
    id: 1147,
    genre: ['R&B', 'Pop'],
    name: 'Justin Timberlake',
    nationality: 'international',
  },
  {
    id: 1562681,
    genre: ['R&B', 'Pop'],
    name: 'Ariana Grande',
    nationality: 'international',
  },
  {
    id: 7543848,
    genre: ['R&B', 'Pop', 'Rap'],
    name: 'Post Malone',
    nationality: 'international',
  },
  {
    id: 3098,
    genre: ['Pop'],
    name: 'George Michael',
    nationality: 'international',
  },
  {
    id: 4050205,
    genre: ['Pop', 'R&B'],
    name: 'The Weeknd',
    nationality: 'international',
  },
  {
    id: 416239,
    genre: ['Pop'],
    name: 'Imagine Dragons',
    nationality: 'international',
  },
  {
    id: 116,
    genre: ['R&B', 'Pop'],
    name: 'Christina Aguilera',
    nationality: 'international',
  },
  {
    id: 17,
    genre: ['R&B', 'Pop'],
    name: 'Usher',
    nationality: 'international',
  },
  {
    id: 1020109,
    genre: ['R&B', 'Pop'],
    name: 'The Black Eyed Peas',
    nationality: 'international',
  },
  {
    id: 269793622,
    genre: ['Pop'],
    name: 'Shakira',
    nationality: 'international',
  },
  {
    id: 415,
    genre: ['Rock'],
    name: 'Nirvana',
    nationality: 'international',
  },
  {
    id: 170,
    genre: ['Rock'],
    name: 'Bryan Adams',
    nationality: 'international',
  },
  {
    id: 417645,
    genre: ['Rap'],
    name: 'D12',
    nationality: 'international',
  },
  {
    id: 177098,
    genre: ['Rap'],
    name: 'Sentino',
    nationality: 'polish',
  },
];
